### ISSUE TITLE
Extract the surveys from this repo

### ISSUE THREAD

**Issue by lassik** [johnwcowan/r7rs-work#11]
Many of the documents in this repo are surveys, not specifications. Could we move them into https://github.com/schemedoc/surveys, add other surveys from elsewhere, and publish them all in a central place under scheme.org?

**Comment by johnwcowan** [comment]
Certainly.   It can be done by chasing links from the ImplementationContrasts page and eyeballing what is left.

However, I am not going to do the work myself.  If anyone else wants to do it, that's great.

**Comment by lassik** [comment]
OK. There is now https://doc.scheme.org/surveys/ Will organize and dress it up later.

**Comment by lassik** [comment]
Just realized the Git history isn't kept in the surveys repo. Let me know if I should re-import with the history. It shouldn't be hard with [git-filter-repo](https://github.com/newren/git-filter-repo).

**Comment by johnwcowan** [comment]
No reason to worry about it, since almost all the text is mine.

ImplementationContrasts should become the root page, README.md.

**Comment by lassik** [comment]
I imported the history anyway. git filter-repo made it really easy.

The front page https://doc.scheme.org/surveys/ is now a copy of ImplementationContrasts with the title changed to "Scheme surveys".
