### ISSUE TITLE
ConditionsCowan seems to need update to properly reflect the released compound objects

### ISSUE THREAD

**Issue by arvyy** [johnwcowan/r7rs-work#31]
In particular, what is `make-compound-type-properties`?

**Comment by johnwcowan** [comment]
I've revamped the spec extensively to fit SRFI 222.  If you think there are issues, let me know.

**Comment by arvyy** [comment]
There is still reference to `make-compound-type-properties` which isn't quite clear to me what it is. My guess would be this is generalization of what `error-object-message` does, ie search for pairs in subobjects list, and merge the cdr of pairs whose cars match the parameter.

Also, a question on how should `condition-properties` interact with r6rs compound type?

**Comment by johnwcowan** [comment]
I meant to remove `compound-properties`; now I've done it.
