### ISSUE TITLE
UrisCowan: `uri-reference?` purpose

### ISSUE THREAD

**Issue by arvyy** [johnwcowan/r7rs-work#34]
`uri-reference?` is either URI or relative reference. What kind of value should satisfy `uri-object?` but not `uri-reference?`

**Comment by johnwcowan** [comment]
If you invoke `(make-uri-object 'username "cowan")`, the result satisfies
`uri-object?` because it is a URI object, but not `uri-reference?`,
`absolute-uri?`, or `relative-reference?`.
