### ISSUE TITLE
UrisCowan data scheme parsing parameters

### ISSUE THREAD

**Issue by arvyy** [johnwcowan/r7rs-work#36]
Currently, `uri-parse-data` returns two values: media type and decoded data. However, media type itself can have multiple parameters encoded within. Maybe it'd be sensible to return 3 values, and add parsed parameters as an alist to the returned value set? Parameter parsing needs to be done either way to pull out charset parameter in case of textual content.

**Comment by johnwcowan** [comment]
+1
